name: Ciphey
# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      string:
        description: 'String to check with Ciphey'
        default: 'SGVsbG93b3JsZA=='
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ciphey:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Set up Python environment
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip' 
    - run: pip install -r requirements.txt
      
    - name: Run Ciphey
      run: ciphey -q -t ${{ github.event.inputs.string }}
