name: Ignorant Number Check

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      CountryCode:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Please enter the numbers country code'
        # Default value if no value is explicitly provided
        default: '44'
        # Input has to be provided for the workflow to run
        required: true
        type: string
        
      number:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Number to check with Ignorant'
        # Default value if no value is explicitly provided, exanple from https://github.com/megadose/ignorant?tab=readme-ov-file#-example
        default: '644637111'
        # Input has to be provided for the workflow to run
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ignorant:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Set up Python environment
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip' 
    - run: pip install -r requirements.txt
        
    - name: Check inputs
      run: echo "Checking +${{ github.event.inputs.CountryCode }} ${{ github.event.inputs.number }} - Please wait..."
      
    - name: Run Ignorant
      run: ignorant ${{ github.event.inputs.CountryCode }} ${{ github.event.inputs.number }} --only-used
