name: MailGoose
# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      domain:
        description: 'Domain'
        default: 'example.com'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  MailGoose:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: Git Clone
      run: git clone https://github.com/CERT-Polska/mailgoose mailgoose

    - name: copy env
      working-directory: ./mailgoose
      run: |
        cp env.example .env 
        docker compose up --build
        curl -X POST http://127.0.0.1:8000/api/v1/check-domain?domain=${{ github.event.inputs.domain }}
