name: XSSTrike

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      domain:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'URL to XSSStrike'
        # Default value
        default: 'google.com'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  XSStrike:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Set up Python environment
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
      
    # Run with the provided input
    - name: git clone
      run: git clone https://github.com/s0md3v/XSStrike.git XSStrike

    - name: Run XSStrike
      working-directory: ./XSStrike
      run: python xsstrike.py -u "${{ github.event.inputs.domain }}"
